# Download the official tables this checkout needs, via the jsDelivr mirror.
#
# raw.githubusercontent.com is measured at ~378 s for a 14 MB file on this network (and on a machine whose
# hosts file points that name at 127.0.0.1 it cannot be reached at all); jsDelivr serves the same repo in a
# few seconds — though activity_table.json alone has been seen at 130-320 s, so expect one slow file.
# The cache layout is the one tools/build-data.mjs expects:
#   <repo>/.cache/gamedata/<path relative to zh_CN/gamedata/>
#
# excel/charword_table.json is not read by build-data.mjs: tools/fetch-assets.mjs uses it for the operators'
# official battle voice (tools/assets/audio.mjs indexVoice), and it is listed here so a fresh checkout can
# prepare both pipelines from one command.
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$Root = Split-Path -Parent $PSScriptRoot
$Cache = Join-Path $Root '.cache\gamedata'
$Base = 'https://cdn.jsdelivr.net/gh/Kengxxiao/ArknightsGameData@master/zh_CN/gamedata/'

$Files = @(
  'excel/activity_table.json',
  'excel/character_table.json',
  'excel/skill_table.json',
  'excel/range_table.json',
  'excel/uniequip_table.json',
  'excel/battle_equip_table.json',
  'excel/enemy_handbook_table.json',
  'excel/charword_table.json',
  'levels/enemydata/enemy_database.json'
)

# Wave / stage level files, read from scripts/gamedata-levels.txt (generated by reproducing
# build-data.mjs's own levelPath() over act2autochess; regenerate with scripts/gen-level-list.mjs).
$LevelList = Join-Path $PSScriptRoot 'gamedata-levels.txt'
if (-not (Test-Path $LevelList)) { Write-Host "missing $LevelList" -ForegroundColor Red; exit 1 }
foreach ($l in Get-Content $LevelList) { if ($l.Trim()) { $Files += $l.Trim() } }

$total = 0
$missing = @()
$failed = @()
foreach ($f in $Files) {
  $dest = Join-Path $Cache ($f -replace '/', '\')
  New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
  if ((Test-Path $dest) -and (Get-Item $dest).Length -gt 0) {
    Write-Host ("  skip (cached) {0,-42} {1,12:N0} bytes" -f $f, (Get-Item $dest).Length)
    $total += (Get-Item $dest).Length
    continue
  }
  $sw = [Diagnostics.Stopwatch]::StartNew()
  # The table spells the mirror wave variants with an upper-case `_S`, the upstream repo stores them
  # lower-case (`level_act1autochess_h07_01_s.json`, confirmed via the GitHub contents API). Windows does
  # not care, GitHub does, so try the spelled path first and fall back to the lower-cased one. The file is
  # saved under the name the repo really uses -- that is what build-data.mjs resolves to on Windows.
  $url = $Base + $f
  & curl.exe -s -L --fail -o $dest $url
  $code = $LASTEXITCODE
  if ($code -eq 22) {
    $lower = ($f -replace '_S\.json$', '_s.json')
    if ($lower -ne $f) {
      & curl.exe -s -L --fail -o $dest ($Base + $lower)
      $code = $LASTEXITCODE
      if ($code -eq 0) { $f = $lower; $dest = Join-Path $Cache ($f -replace '/', '\') }
    }
  }
  $sw.Stop()
  if ($code -ne 0) {
    if (Test-Path $dest) { Remove-Item $dest -Force -ErrorAction SilentlyContinue }
    if ($code -eq 22) { Write-Host ("  MISSING upstream (404) {0}" -f $f) -ForegroundColor Yellow; $missing += $f }
    else { Write-Host ("  FAIL curl {0}: {1}" -f $code, $f) -ForegroundColor Red; $failed += $f }
    continue
  }
  $len = (Get-Item $dest).Length
  $total += $len
  Write-Host ("  ok  {0,-42} {1,12:N0} bytes  {2,6:N1}s" -f $f, $len, $sw.Elapsed.TotalSeconds)
}
Write-Host ("`ntotal {0:N1} MB in {1}" -f ($total / 1MB), $Cache)
if ($missing.Count) { Write-Host ("upstream 404 ({0}): {1}" -f $missing.Count, ($missing -join ', ')) -ForegroundColor Yellow }
if ($failed.Count) { Write-Host ("curl failures ({0}): {1}" -f $failed.Count, ($failed -join ', ')) -ForegroundColor Red; exit 1 }
